In [1]:
import numpy as np
import pandas as pd
import os

In [ ]:
# header = 'infer' toma la primer fila como titulos  
df = pd.read_csv('data_studentlist.csv', header = 'infer')
df.head()

In [ ]:
#Modificar encabezado de df
df = df.rename(columns = {
    "name":"NAME",
    "age": "AGE"
})
df.head()

In [ ]:
# encabezado de columnas se pone en mayusculas 
df.columns = [ col.upper() for col in df.columns]
df.head()

In [ ]:
#en cabezado de columnas se pon en minisculas 
df.columns = [ col.lower() for col in df.columns ]
df.head()

In [ ]:
#agrega al inicio 
df = df.add_prefix("prefix_")
#agrega al final 
df = df.add_suffix("_suf")
df.head()

In [ ]:
df.columns = ['NAME', 'GENDER' , 'AGE', 'GRADE', 'ABSENCE', 'BLOODTYPE', 'HEIGHT', 'WEIGHT']
df.head()

In [ ]:
#Agregar una nueva columna a los datos 
df['IMC'] = 1000*df['WEIGHT']/df['HEIGHT']**2
df.head()

In [ ]:
df_left = df.loc[:,['NAME','AGE','GENDER','ABSENCE']]
df_right = df.loc[:,['NAME','BLOODTYPE','WEIGHT','HEIGHT']]

#union df_izq y df_dere , especificar la columna , se devuelve comom una interseccion 
pd.merge(df_left, df_right, left_on='NAME', right_on='NAME', how ="inner")

In [ ]:
df_left_peque = df_left.loc[:10,:]
df_right_peque =df_right.loc[7:,:]

#une las tables una arriba ade otra en orden alfabetico  
pd.concat([df_left_peque,df_right_peque], sort = True)

#axis nos dive sobre que eje opera 1:columnas , 0:filas 
# une dos tablas una a lado de la otra 
pd.concat([df_left_peque,df_right_peque], axis = 1,sort = True)

In [63]:
#Creamos los datos 
columnas = ['A','B','C']
indice_out = ['G1']*2 + ['G2']*2 + ['G3']*2
indice_in = ['a','b']*3

In [64]:
#pares de tupla 
indice_zip = list(zip(indice_out, indice_in))
indice_zip

[('G1', 'a'), ('G1', 'b'), ('G2', 'a'), ('G2', 'b'), ('G3', 'a'), ('G3', 'b')]

In [ ]:
#objeto de multi indice 
multi_indice = pd.MultiIndex.from_tuples(indice_zip)
#creamos el data frame 
df = pd.DataFrame(data = np.random.rand(6,3), index = multi_indice, columns =columnas )
df

In [ ]:
#seleccion de grupo         
df.loc['G1']

#muestra lo que hay en el grupo 1 fila a
df.loc['G1'].loc['a']

A    0.153930
B    0.220650
C    0.224219
Name: a, dtype: float64

In [61]:
df = pd.read_csv('data_studentlist.csv', header = 'infer')

#groupby,    tuplas con el genero y tipo de sangre 
sr = df.groupby(['gender','bloodtype'])['height'].mean()
sr

gender  bloodtype
F       A            172.450000
        AB           170.100000
        B            158.200000
        O            164.433333
M       A            165.700000
        AB           181.050000
        B            174.550000
        O            166.200000
Name: height, dtype: float64

tabla pibote: forma de reorganizar una tabla ya existente o de ordenar otra tabla de datos (reordenar datos)

In [3]:
import numpy as np
import pandas as pd
import os

In [11]:
my_dict = {"Size": ["L", "L", "M", "M", "M", "S", "S", "S", "S"],
            "Type": ["A", "A", "A", "B", "B", "A", "A", "B", "B"],
            "Location": ["L1", "L1", "L1", "L2", "L2", "L1", "L2", "L2", "L1"],
            "A": [1, 2, 2, 3, 3, 4, 5, 6, 7],
            "B": [2, 4, 5, 5, 6, 6, 8, 9, 9]}
df =pd.DataFrame(my_dict)
df

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [8]:
#creacion de tabla pibote 
dfr = pd.pivot_table(df,index = ['Size','Type'],columns = 'Location', values = 'B')
dfr

# las casillas que tienen NAN se van a reemplzar con 0 
dfr = pd.pivot_table(df,index = ['Size','Type'],columns = 'Location', values = 'B', fill_value = 0)
dfr

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [9]:
dfr_1 = pd.pivot_table(df , index =['Size','Type'], columns = 'Location', values = 'B',aggfunc = np.median, fill_value = 0)
dfr_1

C:\Users\6570\AppData\Local\Temp\ipykernel_34212\2031123603.py:1: FutureWarning: The provided callable <function median at 0x00000201E25ADBC0> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  dfr_1 = pd.pivot_table(df , index =['Size','Type'], columns = 'Location', values = 'B',aggfunc = np.median, fill_value = 0)

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [10]:
pd.pivot_table(df, index=['Size','Type'], values = ['A','B'],
               aggfunc ={'A':np.max,'B' :np.min})
# funciones de agregacion aggfuc indica con que valores se van a llenar

C:\Users\6570\AppData\Local\Temp\ipykernel_34212\1117175100.py:1: FutureWarning: The provided callable <function max at 0x00000201E24620C0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pd.pivot_table(df, index=['Size','Type'], values = ['A','B'],
C:\Users\6570\AppData\Local\Temp\ipykernel_34212\1117175100.py:1: FutureWarning: The provided callable <function min at 0x00000201E2462200> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  pd.pivot_table(df, index=['Size','Type'], values = ['A','B'],

           A  B
Size Type
L    A     2  2
M    A     2  5
     B     3  5
S    A     5  6
     B     7  9

In [15]:
from sklearn.datasets import load_iris

In [23]:
data = load_iris()
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [33]:
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df['target'] = data.target
df['species'] = data.target_names[data.target]

# eliminamos la columna species ya que son string 
df.drop(columns = 'species').mean(axis = 0)

#corelacion de variables 
df.loc[:,'sepal length (cm)'].corr(df.loc[:,'sepal width (cm)'])

np.float64(-0.11756978413300208)

In [36]:
# matriz de las correlaciones 
np.round(df.drop(columns = 'species').corr(),3)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
sepal length (cm),1.000,-0.118,0.872,0.818,0.783
sepal width (cm),-0.118,1.000,-0.428,-0.366,-0.427
petal length (cm),0.872,-0.428,1.000,0.963,0.949
petal width (cm),0.818,-0.366,0.963,1.000,0.957
target,0.783,-0.427,0.949,0.957,1.000

In [ ]:
#promedio por columnas de setosa
df[df.species == 'setosa'].mean(numeric_only=True)

In [39]:
#data frame con valores en NAN
datos = {
    'precio': [34, 54, np.nan, np.nan, 56, 12, 34],
    'cantidad_en_stock': [3, 6, 14, np.nan, 5, 2, 10],
    'productos_vendidos': [3, 45, 23, np.nan, 24, 6, np.nan]
}

df = pd.DataFrame(datos)
df.head()

   precio  cantidad_en_stock  productos_vendidos
0    34.0                3.0                 3.0
1    54.0                6.0                45.0
2     NaN               14.0                23.0
3     NaN                NaN                 NaN
4    56.0                5.0                24.0

In [ ]:
mascara = df.isna()
mascara

#cuantos valores nulos tiene cada columna 
df.isna().sum(axis=0)

#cuantos valores nulos tiene cada fila 
df.isna().sum(axis=1)

In [45]:
#eliminar valores faltantes 
df.dropna(axis=0, how='any')#elimna la fila con almenos un valor nulo 
df.dropna(axis=0, how='all')#elimna la fila con mas de un valor null
df.dropna(axis=0,thresh=2)#thresh umbral conserva las filas que tienen al menos dos null

   precio  cantidad_en_stock  productos_vendidos
0    34.0                3.0                 3.0
1    54.0                6.0                45.0
2     NaN               14.0                23.0
4    56.0                5.0                24.0
5    12.0                2.0                 6.0
6    34.0               10.0                 NaN

In [ ]:
#crear una nueva columna con NAN
df['descuento'] = np.nan
df

df.dropna(axis=1,how='any')

In [51]:
df_sin_nan = df.dropna(axis=1,how='all') 
df_sin_nan = df_sin_nan.dropna(axis=0,how='all')
df_sin_nan

   precio  cantidad_en_stock  productos_vendidos
0    34.0                3.0                 3.0
1    54.0                6.0                45.0
2     NaN               14.0                23.0
4    56.0                5.0                24.0
5    12.0                2.0                 6.0
6    34.0               10.0                 NaN

In [54]:
#modificar los nan con 0 
df_sin_nan['productos_vendidos'] = df_sin_nan['productos_vendidos'].fillna(0)
#solo modifico los productos vendidos 
df_sin_nan

#modifica los NAN de precio 
df_sin_nan['precio'] = df_sin_nan['precio'].fillna(df_sin_nan['precio'].mean())
#solo modifico los NAN en precio 
df_sin_nan

   precio  cantidad_en_stock  productos_vendidos
0    34.0                3.0                 3.0
1    54.0                6.0                45.0
2    38.0               14.0                23.0
4    56.0                5.0                24.0
5    12.0                2.0                 6.0
6    34.0               10.0                 0.0

In [ ]:
df = pd.DataFrame({'color':['red','blue','green','red','blue']})
#transformamos las palabras a valores que comprenda la maquina 
one_hot = pd.get_dummies(df['color'])
one_hot

#codificacion (n-1) drop de un color 
one_hot_n1 = pd.get_dummies(df['color'],drop_first=True) 
#elimina una columna para evitar la replica 
one_hot_n1

In [60]:
df = pd.DataFrame({ 'c1': ['a', 'a', 'a', 'b', 'c', 'd'], 
                   'c2': [1, 1, 1, 2, 2, 1],
                   'c3': [1, 1, 2, 2, 2, 1]})

#detecccion de duplicados 
df_dup =df.duplicated()
# True se repite la fila 
df_dup

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool